name: off-dangerbot

on:
  pull_request:
      types: assigned

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Assign reviewer if prompted
      # API token for off-dangerbot
      env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
      run: |
        gem install danger --version '~> 5.0'
        danger --version 
        danger
